export const vaultAbi = [
  {
    type: "function",
    name: "asset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "ticketEngine",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "getBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "getTwab",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "encryptedAmount", type: "bytes32" },
      { name: "inputProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "encryptedAmount", type: "bytes32" },
      { name: "inputProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "totalDeposits",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "makeTotalPubliclyDecryptable",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [{ name: "account", type: "address", indexed: true }],
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [{ name: "account", type: "address", indexed: true }],
  },
] as const;

export const ticketEngineAbi = [
  {
    type: "function",
    name: "indexOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getWeight",
    stateMutability: "view",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "frozen",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "totalTickets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
] as const;

export const drawManagerAbi = [
  { type: "error", name: "InvalidTicketEngine", inputs: [] },
  { type: "error", name: "InvalidVault", inputs: [] },
  { type: "error", name: "DrawNotCommitted", inputs: [] },
  { type: "error", name: "DrawPendingReveal", inputs: [] },
  { type: "error", name: "DrawAlreadyRevealed", inputs: [] },
  { type: "error", name: "DrawNotRevealed", inputs: [] },
  { type: "error", name: "InvalidRevealBlock", inputs: [] },
  { type: "error", name: "DrawIntervalNotElapsed", inputs: [] },
  { type: "error", name: "RevealTooEarly", inputs: [] },
  { type: "error", name: "RevealTooLate", inputs: [] },
  { type: "error", name: "ZeroTotalTickets", inputs: [] },
  { type: "error", name: "ZeroPrize", inputs: [] },
  { type: "error", name: "WrongDrawId", inputs: [] },
  { type: "error", name: "AlreadyChecked", inputs: [] },
  { type: "error", name: "NotRegistered", inputs: [] },
  { type: "error", name: "NotChecked", inputs: [] },
  { type: "error", name: "AlreadyClaimed", inputs: [] },
  { type: "error", name: "AlreadyWinRevealed", inputs: [] },
  { type: "error", name: "NotAWinner", inputs: [] },
  {
    type: "function",
    name: "drawId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "revealed",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "revealBlock",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "drawRandomValue",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    name: "prizeAmountPlain",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    name: "prizeOfDraw",
    stateMutability: "view",
    inputs: [{ name: "draw", type: "uint256" }],
    outputs: [{ name: "prize", type: "uint64" }],
  },
  {
    type: "function",
    name: "lastCommitTimestamp",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "MIN_DRAW_INTERVAL",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "MIN_REVEAL_DELAY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "MAX_REVEAL_WINDOW",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "YIELD_DIVISOR",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "commitDraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "revealBlock_", type: "uint256" },
      { name: "tvlCleartext", type: "uint64" },
      { name: "tvlProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "revealDraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "totalTicketsCleartext", type: "uint64" },
      { name: "decryptionProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "totalTicketsPlain",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    name: "hasChecked",
    stateMutability: "view",
    inputs: [
      { name: "draw", type: "uint256" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "hasClaimed",
    stateMutability: "view",
    inputs: [
      { name: "draw", type: "uint256" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "winRevealed",
    stateMutability: "view",
    inputs: [
      { name: "draw", type: "uint256" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "checkIfWon",
    stateMutability: "nonpayable",
    inputs: [{ name: "_drawId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [{ name: "drawId_", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "revealWin",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_drawId", type: "uint256" },
      { name: "wonCleartext", type: "bool" },
      { name: "decryptionProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getPendingPrize",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "getWonFlag",
    stateMutability: "view",
    inputs: [
      { name: "draw", type: "uint256" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "event",
    name: "DrawCommitted",
    inputs: [
      { name: "drawId", type: "uint256", indexed: true },
      { name: "revealBlock", type: "uint256", indexed: false },
      { name: "prizeAmount", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DrawRevealed",
    inputs: [
      { name: "drawId", type: "uint256", indexed: true },
      { name: "randomValue", type: "uint64", indexed: false },
      { name: "totalTickets", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DrawChecked",
    inputs: [
      { name: "drawId", type: "uint256", indexed: true },
      { name: "account", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "PrizeClaimed",
    inputs: [
      { name: "drawId", type: "uint256", indexed: true },
      { name: "account", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "WinRevealed",
    inputs: [
      { name: "drawId", type: "uint256", indexed: true },
      { name: "account", type: "address", indexed: true },
      { name: "tier", type: "uint8", indexed: false },
    ],
  },
] as const;

export const erc7984Abi = [
  {
    type: "function",
    name: "isOperator",
    stateMutability: "view",
    inputs: [
      { name: "holder", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "setOperator",
    stateMutability: "nonpayable",
    inputs: [
      { name: "operator", type: "address" },
      { name: "until", type: "uint48" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "rate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "wrap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "underlying",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
] as const;

export const underlyingErc20Abi = [
  {
    type: "function",
    name: "mint",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "value", type: "uint256", indexed: false },
    ],
  },
] as const;
